<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\facades\DB;

class Films extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('films')->insert([
            [
                'id' => 1,
                'titre' => 'LE RÈGNE ANIMAL',
                'resume' => 'description',
                'duree' => 128,
                'annee' => '2023',
                'realisateur_id' => '1',
                //'realisateur_id' = 
                //'producteur_id' = 
                'producteur_id' => '1',
                'lienFilm' => 'https://youtu.be/K1pfR_IC7pU?si=JkFmf9PGTfb6ETgD',
                'pochette' => 'https://fr.web.img4.acsta.net/c_310_420/pictures/23/08/28/10/29/4138047.jpg',
                'type' => 'Horror',
                'brand' => '20th Century Fox',
                'cote' => '6.3',
                'rating' => '18 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 2,
                'titre' => 'Killer of the flower moon',
                'resume' => 'description',
                'duree' => 206,
                'annee' => '2023',
                'realisateur_id' => '2',
                'producteur_id' => '2',
                'lienFilm' => 'https://youtu.be/7cx9nCHsemc?si=WRMwLs9BYPxVHmE5',
                'pochette' => 'https://image11.m1905.cn/uploadfile/2023/0907/20230907035323362541.jpg',
                'type' => 'Mystery',
                'brand' => '20th Century Fox',
                'cote' => '3.5',
                'rating' => '14 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 3,
                'titre' => 'THE CREATOR',
                'resume' => 'description',
                'duree' => 133,
                'annee' => '2023',
                'realisateur_id' => '3',
                'producteur_id' => '3',
                'lienFilm' => 'https://youtu.be/ex3C1-5Dhb8?si=xPUMXPwWlK1wtbX9',
                'pochette' => 'https://de.web.img3.acsta.net/c_310_420/pictures/23/08/23/09/55/0062394.jpg',
                'type' => 'Thriller',
                'brand' => '20th Century Fox',
                'cote' => '8.9',
                'rating' => '18 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 4,
                'titre' => 'Forrest Gump',
                'resume' => 'description',
                'duree' => 140,
                'annee' => '2015',
                'realisateur_id' => '4',
                'producteur_id' => '4',
                'lienFilm' => 'https://youtu.be/eYSnxZKTZzU?si=HbmK5-42j-qLEX0S',
                'pochette' => 'https://fr.web.img5.acsta.net/c_210_280/pictures/15/10/13/15/12/514297.jpg',
                'type' => 'Horror',
                'brand' => '20th Century Fox',
                'cote' => '6.7',
                'rating' => '18 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 5,
                'titre' => 'La Liste de Schindler',
                'resume' => 'description',
                'duree' => 195,
                'annee' => '2019',
                'realisateur_id' => '5',
                'producteur_id' => '5',
                'lienFilm' => 'https://youtu.be/gG22XNhtnoY?si=G9f14WKtZa7r6QEH',
                'pochette' => 'https://th.bing.com/th/id/R.8fa2f5bf1a3da8e1cfee9b0dd1f0dcc5?rik=DtTHCTXzjo4VmQ&riu=http%3a%2f%2fimage11.m1905.cn%2fuploadfile%2f2019%2f0218%2f20190218113718390000.jpg&ehk=7l1o5RJ%2bZqii35CNTwCk1Q3UVwOFDp154rsDk1OszZY%3d&risl=&pid=ImgRaw&r=0',
                'type' => 'Mystery',
                'brand' => '20th Century Fox',
                'cote' => '8.2',
                'rating' => '14 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 6,
                'titre' => 'La Ligne verte',
                'resume' => 'description',
                'duree' => 189,
                'annee' => '1999',
                'realisateur_id' => '6',
                'producteur_id' => '6',
                'lienFilm' => 'https://youtu.be/Ki4haFrqSrw?si=pG5RxJ1UlfoeXxIS',
                'pochette' => 'https://th.bing.com/th/id/R.8810b348ae47dcb88c509de9bad9fdbe?rik=%2f2eQTlegDEZlww&riu=http%3a%2f%2ffr.web.img3.acsta.net%2fr_1280_720%2fmedias%2fnmedia%2f18%2f66%2f15%2f78%2f19254683.jpg&ehk=6L9bJpkgheDHKNWvjaXI%2fgetDRoE%2f5d9tGTlzTMt0wk%3d&risl=&pid=ImgRaw&r=0',
                'type' => 'Horror',
                'brand' => '20th Century Fox',
                'cote' => '4.1',
                'rating' => '10 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 7,
                'titre' => '12 hommes en colère',
                'resume' => 'description',
                'duree' => 95,
                'annee' => '2007',
                'realisateur_id' => '7',
                'producteur_id' => '7',
                'lienFilm' => 'https://youtu.be/TEN-2uTi2c0?si=3tEG8cAdNSXOhh0A',
                'pochette' => 'https://th.bing.com/th/id/R.7b7ff005ad220d4c93f5ea71eacf1ccd?rik=Z%2fj1ciDs5DNzog&pid=ImgRaw&r=0',
                'type' => 'Thriller',
                'brand' => '20th Century Fox',
                'cote' => '5.8',
                'rating' => '18 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 8,
                'titre' => 'Le Parrain',
                'resume' => 'description',
                'duree' => 175,
                'annee' => '2022',
                'realisateur_id' => '8',
                'producteur_id' => '8',
                'lienFilm' => 'https://youtu.be/UaVTIH8mujA?si=PRVUi7RGko9E6aDr',
                'pochette' => 'https://www.frenchstreamhd.com/uploads/posts/covers/le-parrain-filmoflix.jpg',
                'type' => 'Thriller',
                'brand' => '20th Century Fox',
                'cote' => '4.5',
                'rating' => '18 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 9,
                'titre' => 'Les Evadés',
                'resume' => 'description',
                'duree' => 142,
                'annee' => '1995',
                'realisateur_id' => '9',
                'producteur_id' => '9',
                'lienFilm' => 'https://youtu.be/2e8Otbbcowc?si=Pc60FOgHCjzP3Khz',
                'pochette' => 'https://i.pinimg.com/originals/9a/0e/e3/9a0ee3a1ac628813a07c7dc3f5a19f5f.png',
                'type' => 'Mystery',
                'brand' => '20th Century Fox',
                'cote' => '1.8',
                'rating' => '10 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
            [
                'id' => 10,
                'titre' => 'Interstellar',
                'resume' => 'description',
                'duree' => 169,
                'annee' => '2014',
                'realisateur_id' => '10',
                'producteur_id' => '10',
                'lienFilm' => 'https://youtu.be/zSWdZVtXT7E?si=X2Mcpecy2drHna69',
                'pochette' => 'https://2.bp.blogspot.com/-5fFGN39--HY/VluI4qsuTII/AAAAAAAACAs/AboW-Kwulro/s400/158828.jpg-r_640_600-b_1_D6D6D6-f_jpg-q_x-xxyxx.jpg',
                'type' => 'Horror',
                'brand' => '20th Century Fox',
                'cote' => '2.5',
                'rating' => '10 et plus',
                'created_at' => '2018-01-11 10:16:32',
            ],
        ]);
    }
}
